name: CI
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install pnpm ï’‡
        run: npm i -g pnpm

      - name: Install dependencies ðŸ”§
        run: pnpm install --frozen-lockfile

      - name: Lint ðŸ–Š
        run: pnpm run check-lint

      - name: set env vars
        run: |
          touch apps/client/.env
          echo NEXT_PUBLIC_CLERK_FRONTEND_API=clerk.8bqex.mkl5j.lcl.dev >> apps/client/.env

      - name: Build client âœ…
        run: cd apps/client && pnpx prisma generate && cd ../.. && pnpm run build
