name: CI
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install pnpm ï’‡
        run: npm i -g pnpm

      - name: Install dependencies ğŸ”§
        run: pnpm install --frozen-lockfile

      - name: Lint ğŸ–Š
        run: pnpm run check-lint

      - name: Build client âœ…
        run: pnpm run build

      - name: Test server ğŸ–¥
        run: pnpm run test
